[project]
name = "pdf-parse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "types-requests>=2.32.0.20241016",
    "rich>=13.7.0",
    "unstructured[all-docs]>=0.12.4",
]
